# strategies for higher-order

SN = (horpo || (hodp;hodg?;(hosccs?;(hosc | horpo))+))

WANDA = (oracle -afsm -p -cmd "./wanda.exe")

AFS = (afstohrs;SN)

KB = (hocr -kb -m 10;SN)!

KB_W = (hocr -kb -m 10;(SN | WANDA))!

REDUNDANT_RHS = ((hocr -closed);(horedundant -rhs))
REDUNDANT_DEV = ((hocr -closed);(horedundant -development 4))
REDUNDANT_DEL = ((hocr -closed);(horedundant -remove 4))
REDUNDANT_DEL1 = ((hocr -closed);(horedundant -remove 1))
REDUNDANT_FC = ((hocr -closed);(horedundant -narrowfwd -narrowbwd))

CLOSED = (if left-linear -ho then (hocr -closed;(hoclosed -trivial | hoclosed -development)) else fail)!

NONCR = (hocr -closed;hononconfluence)

AUTO = (if prs then (\
 KB || CLOSED  || NONCR \
 ) else fail)

COMP = (if prs then (\
  (if left-linear -ho then homodular else fail)?; (\
  (NONCR | REDUNDANT_FC)3*! || \
  (REDUNDANT_DEL?;(CLOSED || KB_W))3*! || \
  (CLOSED | REDUNDANT_RHS)3*! || \
  (CLOSED | REDUNDANT_DEV)3*! || \
  (CLOSED | REDUNDANT_RHS?;REDUNDANT_DEL1?)3*! || \
  (CLOSED | REDUNDANT_DEV?;REDUNDANT_DEL1?)3*! \
  )) else fail)